name: Pipes

on:
    pull_request:
        branches:
            - master
        paths:
            - 'composer.json'
            - '.github/**'
            - 'src/**'
            - 'tests/**'

jobs:
    php74:
        name: PHP 7.4
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'

            -   name: Validate composer.json
                run: composer validate --strict

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-php74-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php74-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress

            -   name: Run checks
                run: composer run check
    php80:
        name: PHP 8.0
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.0'

            -   name: Validate composer.json
                run: composer validate --strict

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-php80-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php80-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress

            -   name: Run checks
                run: composer run check
